# Generated by Django 6.0.6 on 2026-06-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_company',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
