# Generated by Django 6.0.6 on 2026-06-27 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='value',
            new_name='variation_value',
        ),
    ]
