# Generated by Django 6.0.6 on 2026-06-27 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_value_variation_variation_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='variation_value',
            new_name='value',
        ),
    ]
