# Generated by Django 6.0.6 on 2026-06-24 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
